version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: timeplus
    ports:
      - "5432:5432"
    volumes:
      - ./timedb:/var/lib/postgresql/data
